[build] add manual deployment pipeline

diff --git a/.github/workflows/maual-trigger-deploy.yml b/.github/workflows/maual-trigger-deploy.yml
--- a/.github/workflows/maual-trigger-deploy.yml
+++ b/.github/workflows/maual-trigger-deploy.yml
@@ -1,23 +1,55 @@
-name: Workflow Dispatch
+name: Deploy Workflow
 
 on:
   workflow_dispatch:
     inputs:
-      branch_name:
-        description: 'Branch name to trigger the workflow'
-        type: string
+      branch:
+        description: 'Select the branch to deploy'
+        required: true
         default: 'main'
+      environment:
+        description: 'Select the environment'
+        required: true
+        default: 'Develop'
+        type: choice
+        options:
+          - Develop
+          - Release
 
 jobs:
-  build:
+  deploy:
     runs-on: ubuntu-latest
+
+    env:
+      ENVIRONMENT: ''
+
     steps:
-    - uses: actions/checkout@v3
-      with:
-        fetch-depth: 0
-        ref: ${{ github.event.inputs.branch_name }}
-    - run: |
-        echo "The workflow was triggered on branch: ${{ github.event.inputs.branch_name }}"
-    - run: |
-        git checkout ${{ github.event.inputs.branch_name }}
-        # Your build commands here
+      - name: Set up Git repository
+        uses: actions/checkout@v3
+        with:
+          ref: ${{ github.event.inputs.branch }}
+
+      - name: Determine Environment
+        run: |
+          if [ "${{ github.event.inputs.environment }}" == "Develop" ]; then
+            echo "ENVIRONMENT=Development" >> $GITHUB_ENV
+          elif [ "${{ github.event.inputs.environment }}" == "Release" ]; then
+            echo "ENVIRONMENT=Release" >> $GITHUB_ENV
+          fi
+
+      - name: Validate Release Branch (for Release environment only)
+        if: ${{ github.event.inputs.environment == 'Release' }}
+        run: |
+          if [[ ! "${{ github.event.inputs.branch }}" =~ ^releases/ ]]; then
+            echo "Error: Release deployments must use a branch starting with 'releases/'." >&2
+            exit 1
+          fi
+
+      - name: Deploy Application
+        run: |
+          echo "Deploying branch ${{ github.event.inputs.branch }} to $ENVIRONMENT environment"
+          # Add your deployment commands here
+
+      - name: Confirm Deployment
+        run: |
+          echo "Deployment to $ENVIRONMENT environment completed."
